# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myVKApp' do
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'SwiftKeychainWrapper'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/AdMob'

end
target 'myVKAppWidget' do
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'SwiftKeychainWrapper'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/AdMob'

end
target 'myVKAppMessages' do
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'SwiftKeychainWrapper'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/AdMob'

end
target 'myVKAppiMessage' do
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'SwiftKeychainWrapper'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/AdMob'

end
target 'myVKAppWatch Extension' do
  use_frameworks!
platform :watchos, '4.0'
pod 'Alamofire'
pod 'SwiftyJSON'

end