# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myVKApp' do
  use_frameworks!
pod 'Alamofire', '~>4.6.0'
pod 'SwiftyJSON', '~>4.0'
pod 'RealmSwift'

end
