# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myVKApp' do
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'SwiftKeychainWrapper'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

end
target 'myVKAppWidget' do
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'SwiftKeychainWrapper'
pod 'Firebase/Core', '4.9.0'
pod 'Firebase/Auth', '4.9.0'
pod 'Firebase/Database', '4.9.0'

end
target 'myVKAppMessages' do
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'SwiftKeychainWrapper'
pod 'Firebase/Core', '4.9.0'
pod 'Firebase/Auth', '4.9.0'
pod 'Firebase/Database', '4.9.0'

end
target 'myVKAppiMessage' do
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'SwiftKeychainWrapper'
pod 'Firebase/Core', '4.9.0'
pod 'Firebase/Auth', '4.9.0'
pod 'Firebase/Database', '4.9.0'

end